2018-11-22 22:25:36.638 logFileName=用户登陆_1542896736542 [threadPoolTaskExecutor-1][org.jtest.app.log.CustomLogger:26] INFO  testLogger - requesturl is http://test.qmth.com.cn/api/ecs_core/auth/login
2018-11-22 22:25:59.858 logFileName=用户登陆_1542896736542 [threadPoolTaskExecutor-1][org.jtest.app.log.CustomLogger:44] ERROR testLogger - throw an http error
org.apache.http.conn.HttpHostConnectException: Connect to test.qmth.com.cn:80 [test.qmth.com.cn/192.168.10.39] failed: Connection timed out: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.jtest.app.util.HttpClientUtil.httpPost(HttpClientUtil.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jtest.app.controller.run.TestRunController$RunThread.HttpExcute(TestRunController.java:270)
	at org.jtest.app.controller.run.TestRunController$RunThread.runtestcase(TestRunController.java:133)
	at org.jtest.app.controller.run.TestRunController$RunThread.run(TestRunController.java:102)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 20 common frames omitted
2018-11-22 22:25:59.859 logFileName=用户登陆_1542896736542 [threadPoolTaskExecutor-1][org.jtest.app.log.CustomLogger:26] INFO  testLogger - login执行结果为:{"code":0,"errmessage":"Connect to test.qmth.com.cn:80 [test.qmth.com.cn/192.168.10.39] failed: Connection timed out: connect","excuteResult":true}
2018-11-22 22:25:59.859 logFileName=用户登陆_1542896736542 [threadPoolTaskExecutor-1][org.jtest.app.log.CustomLogger:26] INFO  testLogger - 验证点列表:
